Ft favorite articles 159053966
andela/ah-titans pull request #27
Opened 2018-08-08 13:36 UTC by chepmanu

#### What does this PR do?
Setup Postgres database and add .env example

#### Description of tasks to be completed
Ensure that Postgres database is used to store the application data

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ft-favorite-articles-159053966
```
```sh
$ cd ah-titans/authors
```

> Add **.env** file and copy **example.env** content.
> Add your local database configuration settings to your **.env** file

```sh
$ source .env
```
```sh
$ python3.6 -m venv venv
```
```sh
$ source venv/bin/activate
```
```sh
$ pip install -r requirements.txt
```
```sh
$ python manage.py makemigrations
```
```sh
$ python manage.py runserver
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#159053966](https://www.pivotaltracker.com/story/show/159053966)

#### Screenshots
**One favortied articles UI**
![image](https://user-images.githubusercontent.com/28649357/43840272-f3613c3e-9b28-11e8-99f7-08c99f141094.png)

**Favorited articles UI**
![Uploading image.png…]()

2018-08-08 14:26 UTC, petermwash commented
@chepmanu Check on how you have written you PR description. What the PR does and the description are not for this particular PR.

2018-08-08 14:29 UTC, petermwash commented on authors/tests/articles/test_favorite_aritcles.py
> +
Add an end of line here

2018-08-08 14:30 UTC, petermwash commented on authors/templates/static/fav-article.html
> +</html>
Add an end of line.

2018-08-08 15:53 UTC, ronaldndirangu commented
Please resolve the current merge conflict.

2018-08-08 15:55 UTC, ronaldndirangu commented
Also, add postman screenshots to show the response from the requests you've made.

2018-08-08 17:24 UTC, janetnim commented on authors/tests/articles/test_favorite_aritcles.py
> +
Remove unnecessary lines 323-326

2018-08-08 17:33 UTC, migot01 commented on authors/apps/articles/views.py
> +from .models import Article
check your order imports in views.py

2018-08-09 16:32 UTC, janetnim reviewed
in serializers.py
```
favoriteCount = serializers.SerializerMethodField(method_name='get_favorite_count')
```
I think we shouldn't use camel case in naming variables in Python...favorite_count

2018-08-09 16:50 UTC, chepmanu commented
@janetnim 
![image](https://user-images.githubusercontent.com/28649357/43913227-2da05a9e-9c0d-11e8-90f2-e1afecfcec69.png)
The guideline given showed that we had to return it that way.

2018-08-09 17:04 UTC, janetnim commented
Oh okay....missed that

2018-08-09 17:05 UTC, janetnim approved these changes

2018-08-09 17:26 UTC, migot01 approved these changes

2018-08-09 18:07 UTC, johnmusiu requested changes
I need @dcDalin to have a look at `articles/views.py` Pagination feature seems to have been accidentally dropped

2018-08-09 18:07 UTC, johnmusiu commented on authors/apps/articles/serializers.py
> +
I think there is some trailing white space here, check on that

2018-08-09 18:07 UTC, johnmusiu commented on authors/apps/articles/views.py
> -    max_page_size = 10
@dcDalin I need your eyes on this file, check if your pagination feature was not accidentally dropped

2018-08-09 19:55 UTC, chepmanu commented
@johnmusiu Thank you, I had not seen that, that might have been dropped when I fixed the conflicts.It is sorted now.

2018-08-10 09:15 UTC, johnmusiu approved these changes

2018-08-10 09:32 UTC, merged