#159691634 Like dislike comment
andela/ah-titans pull request #29
Opened 2018-08-14 13:19 UTC by chepmanu

#### What does this PR do?
Like and dislike comments.

#### Description of tasks to be completed
An authenticated user should be able to like and dislike comments.

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ft-like-dislike-comment-159691634
```
```sh
$ cd ah-titans/authors
```

> Add **.env** file and copy **example.env** content.
> Add your local database configuration settings to your **.env** file

```sh
$ source .env
```
```sh
$ python3.6 -m venv venv
```
```sh
$ source venv/bin/activate
```
```sh
$ pip install -r requirements.txt
```
```sh
$ python manage.py makemigrations
```
```sh
$ python manage.py runserver
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#159691634](https://www.pivotaltracker.com/story/show/159691634)

#### Screenshots
**Liked and disliked comment  UI**
![image](https://user-images.githubusercontent.com/28649357/44093815-383284ae-9fdd-11e8-9ed1-8f265f3ef2db.png)

**On postman when liking comment**
![image](https://user-images.githubusercontent.com/28649357/44093722-fddb22ac-9fdc-11e8-96b5-fa0789a0fc13.png)
**On postman when disliking comment**
![image](https://user-images.githubusercontent.com/28649357/44093914-72e827de-9fdd-11e8-8e05-27bf067ef1b2.png)

2018-08-14 15:12 UTC, petermwash reviewed
It is a great work @chepmanu but you can check on some details like adding an end of line eg. on line 313 of test_favorite_articles.py and line 51 of models .py

2018-08-15 07:45 UTC, johnmusiu approved these changes

2018-08-15 07:52 UTC, ridgekimani commented on authors/apps/articles/urls.py
> +from .views import ArticleViewSet, RateAPIView,CommentsListCreateAPIView, CommentsDestroyGetCreateAPIView,DislikesAPIView, LikesAPIView, TagListAPIView,FavoriteAPIView, CommentLikesAPIView
Imports in a group can be placed in braces. It is for legibility.

2018-08-15 13:31 UTC, dcDalin approved these changes

2018-08-16 18:10 UTC, johnmusiu requested changes
I think this PR should be deleted or rejected since there is a similar one that has been raised to replace this one. Here is the link https://github.com/andela/ah-titans/pull/32

2018-08-17 11:38 UTC, closed without merging