159053969 add search functionality
andela/ah-titans pull request #30
Opened 2018-08-15 02:42 UTC by migot01

#### What does this PR do?
Setup creates search functionality

#### Description of tasks to be completed
Ensure that users can search for articles based on article title, author and  tags

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ft-add-search-functionality-159053969
```
```sh
$ cd ah-titans/authors
```

> Add **.env** file and copy **example.env** content.
> Add your local database configuration settings to your **.env** file
```sh
$ python3.6 -m venv venv
```
```sh
$ source venv/bin/activate
```
```sh
$ source .env
```
```sh
$ pip install -r requirements.txt
```
```sh
$ python manage.py makemigrations
```
```sh
$ python manage.py runserver
```
```sh
Using postman, send a post request to the URL http://127.0.0.1:8000/api/articles?title=title
to search for a title and http://127.0.0.1:8000/api/articles?tags=tag
to search for article with the specific tag  and http://127.0.0.1:8000/api/articles?author=username
to search for the author
Refer to the screenshots below.
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#159053969](https://www.pivotaltracker.com/story/show/159053969)

#### Screenshots:
#### The UI
![image](https://user-images.githubusercontent.com/29063646/44128835-c7533f5a-a04d-11e8-969e-f0552c4cbe5c.png)

![image](https://user-images.githubusercontent.com/29063646/44128857-ed590d88-a04d-11e8-8c80-e994dd4d6089.png)

2018-08-15 06:46 UTC, ronaldndirangu requested changes
Please add the postman screenshots to show the working of the endpoints.

2018-08-15 07:41 UTC, janetnim approved these changes

2018-08-15 08:18 UTC, petermwash commented
@ronaldndirangu Postman screenshots added.

2018-08-15 13:32 UTC, dcDalin approved these changes

2018-08-16 14:50 UTC, chepmanu commented
You have done a good job adhering to  pep8 though some lines are long such as this in your test_filter.py file.
<img width="784" alt="screen shot 2018-08-16 at 17 43 51" src="https://user-images.githubusercontent.com/28649357/44215788-0794a980-a17c-11e8-91e2-c52817f4324f.png">
My suggestion is to do it this way to make it less than 80 characters long. This makes the code cleaner and reading easier as you already know.
<img width="546" alt="screen shot 2018-08-16 at 17 46 01" src="https://user-images.githubusercontent.com/28649357/44215879-4591cd80-a17c-11e8-91ba-60514be8a1ce.png">
Otherwise nice work.

2018-08-16 18:19 UTC, ronaldndirangu approved these changes

2018-08-17 07:44 UTC, johnmusiu requested changes

2018-08-17 07:44 UTC, johnmusiu commented on authors/testrunner.py
> +        return super(TestRunner, self).setup_databases(**kwargs)
Add newline here

2018-08-17 07:44 UTC, johnmusiu commented on authors/templates/static/css/styles.css
> +.search {
add space before new style block

2018-08-17 07:44 UTC, johnmusiu commented on authors/templates/static/css/styles.css
> +
delete unnecessary newline

2018-08-17 07:44 UTC, johnmusiu commented on authors/templates/all-articles.html
> +    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script> -->
remove commented out line

2018-08-17 07:44 UTC, johnmusiu commented on authors/templates/all-articles.html
> +            <!-- <div>
Delete commented out line of code

2018-08-17 07:44 UTC, johnmusiu commented on authors/apps/articles/views.py
> +
Delete newline (only 2 newlines required before class)

2018-08-17 07:44 UTC, johnmusiu commented on authors/apps/articles/views.py
> +class CommentsDestroyGetCreateAPIView(generics.DestroyAPIView, generics.RetrieveAPIView, generics.CreateAPIView,generics.UpdateAPIView):
There is a `generics.RetrieveUpdateDestroyAPIView` which could replace 3 of these parameters passed here.
Also it might be better to do an import at the top for this  ie. `from rest_framework.generics import RetrieveUpdateDestroyAPIView` then pass `RetrieveUpdateDestroyAPIView` as an argument there. I'll also check if there is a single CRUD import for the same

2018-08-17 07:44 UTC, johnmusiu commented on authors/settings.py
> +TEST_RUNNER = 'authors.testrunner.TestRunner'
End of file newline missing here, kindly add one

2018-08-17 07:44 UTC, johnmusiu commented on authors/templates/all-articles.html
> +                    <div class="nav-wrapper">
This block of code is not properly indented, kindly look into it

2018-08-17 11:41 UTC, johnmusiu approved these changes

2018-08-18 08:13 UTC, merged