#159691609 Track Comment Edit History
andela/ah-titans pull request #31
Opened 2018-08-16 06:54 UTC by johnmusiu

#### What does this PR do?
Implements track comment edit history

#### Description of tasks to be completed
List of implemented features:
1. User can edit their comment 
2. A comment should indicate it was edited
3. User should see their comment edit history

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans/tree/ft-track-comment-edit-history-159691609
```
```sh
$ cd ah-titans
```
> Create a virtual environment and activate it.

```sh
$ virtualenv -p python3 venv
```
```sh
$ source venv/bin/activate
```

> Add **.env** file and copy **example.env** content.

``` cp example.env .env```

> Add your local configuration settings to your **.env** file

```sh
$ source .env
```

```sh
$ pip install -r requirements.txt
```

```sh
$ python manage.py makemigrations
```

```sh
$ python manage.py migrate
```

```sh
$ python manage.py runserver
```

Now you can test the various endpoint on the postman.

#### Any background context you want to provide?
None.

#### What are the relevant Pivotal Tracker Stories?
[#159691609](https://www.pivotaltracker.com/story/show/159691609)

#### Relevant screenshots
> Edit a comment
![image](https://user-images.githubusercontent.com/12577659/44192734-405f5f00-a139-11e8-8229-8fae8417e858.png)

> Get edit history
![image](https://user-images.githubusercontent.com/12577659/44192813-7c92bf80-a139-11e8-901d-0cdff7f7a1fd.png)

#### Relevant templates
![image](https://user-images.githubusercontent.com/12577659/44192438-0fcaf580-a138-11e8-9283-b4ec775f1bd0.png)

2018-08-16 07:18 UTC, dcDalin approved these changes

2018-08-16 13:43 UTC, janetnim approved these changes

2018-08-16 13:46 UTC, janetnim commented
I think you should give a screenshot of the template of how the edit history of a comment will look like

2018-08-16 13:47 UTC, janetnim requested changes
I think you should give a screenshot of the template of how the edit history of a comment will look like

2018-08-16 14:56 UTC, chepmanu commented
Looks good to me.

2018-08-16 18:22 UTC, migot01 approved these changes

2018-08-17 07:48 UTC, migot01 requested changes

2018-08-17 07:48 UTC, migot01 commented on authors/tests/articles/test_comments.py
> -
Nice work , though you should remove the extra line here

2018-08-17 07:51 UTC, migot01 approved these changes

2018-08-17 08:27 UTC, janetnim approved these changes

2018-08-17 09:51 UTC, merged