#160410718 Update email reset link to point to the front-end
andela/ah-titans pull request #37
Opened 2018-09-12 08:51 UTC by dcDalin

#### What does this PR do?
Changes the reset password link to point to the front-end

#### Description of tasks to be completed
Ensure that when a user clicks on the reset password email link, they are redirected to the front-end

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans.git
```
```sh
$ git checkout -b ch-update-link-160410718
```
```sh
$ cd ah-titans/authors
```

> Add **.env** file and copy **example.env** content.
> Add your local database configuration settings to your **.env** file

```sh
$ source .env
```
```sh
$ python3.6 -m venv venv
```
```sh
$ source venv/bin/activate
```
```sh
$ pip install -r requirements.txt
```
```sh
$ python manage.py makemigrations
```
```sh
$ python manage.py runserver
```

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160410718](https://www.pivotaltracker.com/story/show/160410718)

2018-09-12 12:25 UTC, janetnim approved these changes

2018-09-12 12:28 UTC, migot01 approved these changes

2018-09-13 10:31 UTC, petermwash approved these changes

2018-09-13 10:32 UTC, johnmusiu requested changes

2018-09-13 10:32 UTC, johnmusiu commented on authors/apps/authentication/templates/reset-password-mail.html
> +                                <a class="email-masthead_name">Hi {{ user.email }},</a>
I suppose this ought to be addressed to a `username` as opposed to an `email address`. kindly look into this

2018-09-13 11:05 UTC, merged